#### 2. Design a layer that returns the leading half of the Fourier coefficients of the data.

In [1]:
import torch
from torch import nn, Tensor
from torch.fft import fft

class FourierSplitter(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X: Tensor) -> Tensor:
        fft_result: Tensor = fft(X, dim=-1)
        half : int= fft_result.shape[-1] // 2
        return fft_result[:, :half]

fourier_layer = FourierSplitter()

_range: Tensor = torch.arange(1, 8+1)
X: Tensor = torch.cat((_range, _range.flip(0)), dim=-1).view(2, 8)

full_fft: Tensor = fft(X, dim=-1)
y: Tensor = fourier_layer(X)

print("Input Sequences:")
print(X)
print()
print("Full FFT:")
print(full_fft)
print()
print("Leading Half of the FFT:")
print(y)

Input Sequences:
tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [8, 7, 6, 5, 4, 3, 2, 1]])

Full FFT:
tensor([[36.+0.0000j, -4.+9.6569j, -4.+4.0000j, -4.+1.6569j, -4.+0.0000j,
         -4.-1.6569j, -4.-4.0000j, -4.-9.6569j],
        [36.+0.0000j,  4.-9.6569j,  4.-4.0000j,  4.-1.6569j,  4.+0.0000j,
          4.+1.6569j,  4.+4.0000j,  4.+9.6569j]])

Leading Half of the FFT:
tensor([[36.+0.0000j, -4.+9.6569j, -4.+4.0000j, -4.+1.6569j],
        [36.+0.0000j,  4.-9.6569j,  4.-4.0000j,  4.-1.6569j]])
